@startuml
'https://plantuml.com/activity-diagram-beta

start
:User executes find command;
if () then ([is Field given])
  :Search given field for keyword(s);
else
:Search all fields for keyword(s);
endif
:Display list of matched people;
stop

@enduml
