@startuml

start
:User enters clear command;
:Confirmation window is opened;
if () then (
[User confirms action])
  :  All contacts and meetings are cleared  ;
else ([User cancels action])
endif
:Confirmation window closes;
stop

@enduml
