@startuml
!include Style.puml
hide footbox

box Logic LOGIC_COLOR_T1
participant ":LogicManager" as LogicManager LOGIC_COLOR
participant ":ContactDetailsParser" as ContactDetailsParser LOGIC_COLOR
participant ":EditCommandParser" as EditCommandParser LOGIC_COLOR
participant "editCommand:EditCommand" as EditCommand LOGIC_COLOR
end box

note left of LogicManager: personToEdit is the Person object\n encompassing the edited contact
-> LogicManager : executeContactDetailsCommand\n(edit n/Jack, personToEdit)
LogicManager -> ContactDetailsParser : parseCommand\n(edit n/Jack, personToEdit)
ContactDetailsParser -> EditCommandParser : parse(n/Jack, personToEdit)
ref over EditCommandParser, EditCommand : The more detailed parsing of each field to edit
EditCommand --> EditCommandParser : editCommand
EditCommandParser --> ContactDetailsParser : editCommand
ContactDetailsParser --> LogicManager : editCommand
note right of LogicManager : model is the list of contacts
LogicManager -> EditCommand : execute(model)
EditCommand --> LogicManager : commandResult
<-- LogicManager: commandResult
@enduml

