@startuml
!include style.puml
'https://plantuml.com/activity-diagram-beta

start
:User executes add or view command;
if (is Add command) then (Yes)
    :AddressbookStorage saves contact with details added;
else (is View Command)
    endif
:Open contact details window;
repeat
    :User executes edit command;
    :AddressbookStorage saves changes;
repeat while (User wants to make more edits?) is (yes)
:User executes back command;
stop
@enduml
